abi = [
    {
        "inputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "name": "companies",
        "outputs": [
            {"internalType": "string", "name": "partyName", "type": "string"},
            {"internalType": "string", "name": "currencyCode", "type": "string"},
            {"internalType": "bool", "name": "active", "type": "bool"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "name": "countries",
        "outputs": [
            {"internalType": "string", "name": "name", "type": "string"},
            {"internalType": "string", "name": "code", "type": "string"},
            {"internalType": "string", "name": "code3", "type": "string"},
            {"internalType": "uint256", "name": "codeNumeric", "type": "uint256"},
            {"internalType": "bool", "name": "active", "type": "bool"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "name": "currencies",
        "outputs": [
            {"internalType": "string", "name": "name", "type": "string"},
            {"internalType": "string", "name": "code", "type": "string"},
            {"internalType": "uint8", "name": "digits", "type": "uint8"},
            {"internalType": "uint256", "name": "rounding", "type": "uint256"},
            {"internalType": "string", "name": "symbol", "type": "string"},
            {"internalType": "uint256", "name": "numericCode", "type": "uint256"},
            {"internalType": "bool", "name": "active", "type": "bool"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "string", "name": "_partyName", "type": "string"},
            {"internalType": "string", "name": "_currencyCode", "type": "string"},
        ],
        "name": "insertCompany",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "string", "name": "_name", "type": "string"},
            {"internalType": "string", "name": "_code", "type": "string"},
            {"internalType": "string", "name": "_code3", "type": "string"},
            {"internalType": "uint256", "name": "_codeNumeric", "type": "uint256"},
        ],
        "name": "insertCountry",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "string", "name": "_name", "type": "string"},
            {"internalType": "string", "name": "_code", "type": "string"},
            {"internalType": "uint8", "name": "_digits", "type": "uint8"},
            {"internalType": "uint256", "name": "_rounding", "type": "uint256"},
            {"internalType": "string", "name": "_symbol", "type": "string"},
            {"internalType": "uint256", "name": "_numericCode", "type": "uint256"},
        ],
        "name": "insertCurrency",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "string", "name": "_name", "type": "string"}],
        "name": "insertParty",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "string", "name": "_name", "type": "string"},
            {"internalType": "string", "name": "_description", "type": "string"},
            {"internalType": "string", "name": "_suffixCode", "type": "string"},
        ],
        "name": "insertProduct",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "name": "parties",
        "outputs": [
            {"internalType": "string", "name": "name", "type": "string"},
            {"internalType": "bool", "name": "active", "type": "bool"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "name": "products",
        "outputs": [
            {"internalType": "string", "name": "name", "type": "string"},
            {"internalType": "string", "name": "description", "type": "string"},
            {"internalType": "string", "name": "suffixCode", "type": "string"},
            {"internalType": "bool", "name": "active", "type": "bool"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
]
